In [1]:
# on dictionaries

In [2]:
str = "asdfasf"
print (type(str))

<class 'str'>


In [5]:
data = {}
data[1] = ['one']
data[2] = ['two']
data[3] = ['three']
data[4] = ['four']
print (type (data))

<class 'dict'>


In [7]:
print (data)
print (len (data))

{1: ['one'], 2: ['two'], 3: ['three'], 4: ['four']}
4


In [9]:
dod = {}
dod['one']=[{'a':'aaa', 'b':'bbb', 'c':'ccc'}]
print (dod)

{'one': [{'c': 'ccc', 'a': 'aaa', 'b': 'bbb'}]}


In [10]:
dod2 = {}
dod2['one']=[{'a':'aaa'}]
print (dod2)

{'one': [{'a': 'aaa'}]}


In [ ]:
# on list indexing

# if no index is specified: it means that the extreme one
# for -ve index: add it to the positive max and then take that value on that place. for example look below
# tl = [1, 2, 3, 4]
# tl[-3] == tl[4-3] == tl[1]
# tl[-1] == tl[4-1] == tl[3]
# tl[-4] == tl[4-4] == tl[4]
# tl[ :-3] == tl[ :4-3] == tl[ :1] == tl[0:1]

In [10]:
tl = [1, 2, 3, 4]
print (tl[0])
print (tl[-1])
print (tl[0:4])
print (tl[0: ])
print (tl[ : ])
print (tl[ :3])
print (tl[ :-2])
print (tl[-4])
print (len(tl))

1
4
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3]
[1, 2]
1
4


In [2]:
# on multidimensional lists
l = []
ll = []
print(ll)
l.append(0)
l.append(8)
l.append(4)
ll.append(l.copy())    # without copy(), the reference will be placed, which is not immutable to future changes in l
print(ll)
# print(max(l))

l.append(9)
l.append(3)
l.append(7)
ll.append(l.copy())
print(ll)
print(ll[1])

[]
[[0, 8, 4]]
[[0, 8, 4], [0, 8, 4, 9, 3, 7]]
[0, 8, 4, 9, 3, 7]


In [8]:
# on tuples

import numpy as np

tup3 = "a", "b", "c", "d"
print(tup3)
print(tup3[0])
data = np.zeros((10, 20, 3), dtype=np.uint8)
data_shape = data.shape
print(data_shape[0])
print(len(data_shape))

('a', 'b', 'c', 'd')
a
10
3


In [6]:
# on numpy array axis

import numpy as np
x = np.array([[0, 0, 0],
       [1, 2, 3],
       [2, 2, 2],
       [9, 9, 9]])
print(x.shape)
print(x.sum(axis=0))
print(x.sum(axis=1))    # same as -1
print(x.sum(axis=-1))   # the last axis

(4, 3)
[12 13 14]
[ 0  6  6 27]
[ 0  6  6 27]
